# Basic config
baseURL = "https://miraikumiko.github.io"
theme = "hugo-bearcub"
copyright = "Mirai Kumiko (CC BY 4.0)"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "Mirai Kumiko's website"
    languageName = "üá∫üá∏"
    LanguageCode = "en-US"
    contentDir = "content/en"
    [languages.en.params]
      madeWith = "Personal site"
  [languages.es]
    title = "Sitio web de Mirai Kumiko"
    languageName = "üá™üá∏"
    LanguageCode = "es-ES"
    contentDir = "content/es"
    [languages.es.params]
      madeWith = "Sitio personal"
  [languages.ru]
    title = "–ë–ª–æ–∂–∏–∫ Mirai Kumiko"
    languageName = "üá∑üá∫"
    LanguageCode = "ru-RU"
    contentDir = "content/ru"
    [languages.ru.params]
      madeWith = "–ü–µ—Ä—Å–æ–Ω–∞–ª—å–Ω—ã–π —Å–∞–π—Ç"

[params]
  # The description of your website
  description = "Mirai Kumiko's website"

  # The path to your favicon
  favicon = "images/favicon.png"

  # These images will show up when services want to generate a preview of a link
  # to your site. Ignored if `generateSocialCard = true`. For more information
  # about previews, see https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph
  images = ["images/share.webp"]

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "Mirai Kumiko's website"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = false

  # (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
  # "herman". The former is what you see on Bear Cub's demo (an optimized
  # version of Hugo Bear Blog), while the latter has a more modern look based on
  # Herman Martinus's version of the Blogster Minimal theme for Astro.
  themeStyle = "original"

  # (EXPERIMENTAL) This theme is capable of dynamically generating social cards
  # for posts that don't have `images` defined in their front matter; By setting
  # `generateSocialCard` to false, you can prevent this behavior. For more
  # information see layouts/partials/social_card.html
  generateSocialCard = true

  # Social media. Delete any item you aren't using to make sure it won't show up
  # in your website's metadata.
  [params.social]
    mastodon = "miraikumiko" # Twitter handle (without '@')
    instagram = "miraikumiko" # Facebook Page Admin ID

  # Author metadata. This is mostly used for the RSS feed of your site, but the
  # email is also added to the footer of each post. You can hide the "reply to"
  # link by using a `hideReply` param in front matter.
  [params.author]
    name = "Mirai Kumiko"
    email = "murrr@macaw.me"
